name: Economy
version: '1.0'

main: me.mrfavio.economy.Economy
api-version: '26.1.2'
commands:
  info:
    description: Check how to use all commands.
    usage: /info
  bal:
    description: Check your current balance.
    aliases: [money, balance]
  pay:
    description: Pay money to another player.
    usage: /pay <player> <amount>
  eco:
    description: Manage server economy (Admin only).
    usage: /eco <give/take/set> <player> <amount>
    permission: economy.admin
  buyorder:
    description: Creates chest shop buy order.
    usage: /buyorder <item> <amount> <price>
  sellorder:
    description: Creates chest shop sell order.
    usage: /sellorder <item> <amount> <price>
  deleteshop:
    description: Deletes chest shop.
    usage: /deleteshop
  adminbuyorder:
    description: Create an unlimited admin buy shop (Admin only).
    usage: /adminbuyorder <item> <amount> <price>
    permission: economy.admin
  adminsellorder:
    description: Create an unlimited admin sell shop (Admin only).
    usage: /adminsellorder <item> <amount> <price>
    permission: economy.admin