name: Economy
version: '1.2'

main: me.mrfavio.economy.Economy
api-version: '26.1.2'
commands:
  info:
    description: Check how to use all commands.
    usage: /info
  bal:
    description: Check your current balance.
    aliases: [money, balance]
  pay:
    description: Pay money to another player.
    usage: /pay <player> <amount>
  eco:
    description: Manage server economy (Admin only).
    usage: /eco <give/take/set> <player> <amount>
    permission: economy.admin
  buyorder:
    description: Creates chest shop buy order using the item in your hand.
    usage: /buyorder <amount> <price>
  sellorder:
    description: Creates chest shop sell order using the item in your hand.
    usage: /sellorder <amount> <price>
  deleteshop:
    description: Deletes chest shop.
    usage: /deleteshop
  adminbuyorder:
    description: Create an unlimited admin buy shop using the item in your hand (Admin only).
    usage: /adminbuyorder <amount> <price>
    permission: economy.admin
  adminsellorder:
    description: Create an unlimited admin sell shop using the item in your hand (Admin only).
    usage: /adminsellorder <amount> <price>
    permission: economy.admin